### ISSUE TITLE
Headphone not listed

### ISSUE THREAD

**Issue by elmerehbi** [kgaut/gnome-shell-audio-output-switcher#2]
Hello,

Thanks for a great extension.
Headphone is not listed. Could you please add it?

Thanks

**Comment by kgaut** [comment]
@elmerehbi : this extension list all devices that pulse-audio aknowledge. Are your headphones plugged in ? and displayed under sound / output settings ?

![2016-05-30-07 52 07-screenshot](https://cloud.githubusercontent.com/assets/736910/15640740/791de0c6-263b-11e6-94a4-e7ec67e8874d.png)

**Comment by elmerehbi** [comment]
@kgaut Pulse audio does list the headphone with & without having them connected but it doesn't appear in your extension.

![sound_001](https://cloud.githubusercontent.com/assets/3155152/15753237/53f68924-28f2-11e6-9c9e-7f2c1a897de2.png)

PS: Headphones do work but sometimes I wish to switch to headphones without having the headphones plugged in.

**Comment by kgaut** [comment]
Thanks for theses details, I'll see what I can do.

**Comment by criztovyl** [comment]
I always thought you can't output to speakers and headphones simultaneously b/c hardware does not allow this.
In my settings there isn't even a distincting between Speakers and Headphones: With Headphones plugged in "Headphones" is listed, otherwise "Speakers".

No Headphones:
![sp](https://cloud.githubusercontent.com/assets/2174918/22205926/464a8f7e-e179-11e6-85e9-de033776b421.png)
Headphones:
![hp](https://cloud.githubusercontent.com/assets/2174918/22205925/4649fec4-e179-11e6-85a1-2d02700c19ad.png)
